events {
  worker_connections 1024;
}

http {
  server {
    listen 80;

    location / {
      proxy_pass http://frontend:3000;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/auth/ {
      proxy_pass http://auth:8005/;
      proxy_set_header Host $host;
      proxy_set_header Authorization $http_authorization;
    }

    location /api/upload/ {
      proxy_pass http://upload:8001/;
      proxy_set_header Host $host;
      proxy_set_header Authorization $http_authorization;
      client_max_body_size 500M;
    }

    location /api/download/ {
      proxy_pass http://download:8002/;
      proxy_set_header Host $host;
      proxy_set_header Authorization $http_authorization;
    }

    location /api/admin/ {
      proxy_pass http://admin:8003/;
      proxy_set_header Host $host;
      proxy_set_header Authorization $http_authorization;
    }

    location /api/ai/ {
      proxy_pass http://ai:8004/;
      proxy_set_header Host $host;
      proxy_set_header Authorization $http_authorization;
    }
  }
}