events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        # 1️⃣ Le Frontend React (L'interface web)
        location / {
            proxy_pass http://172.25.0.30:3000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Redirection vers ms-auth (IP interne: 172.25.0.20, port interne: 8005)
        location /api/auth/ {
            proxy_pass http://172.25.0.20:8005/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Redirection vers ms-upload (IP interne: 172.25.0.21, port interne: 8001)
        location /api/upload/ {
            proxy_pass http://172.25.0.21:8001/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Redirection vers ms-download (IP interne: 172.25.0.22, port interne: 8002)
        location /api/download/ {
            proxy_pass http://172.25.0.22:8002/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Redirection vers ms-admin (IP interne: 172.25.0.23, port interne: 8003)
        location /api/admin/ {
            proxy_pass http://172.25.0.23:8003/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Redirection vers ms-ai (IP interne: 172.25.0.24, port interne: 8004)
        location /api/ai/ {
            proxy_pass http://172.25.0.24:8004/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}